repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.3
    hooks:
    -   id: autopep8
        args: ['-i', '--select=E,F', '--exclude=src/filters, src/parser/evaql']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-typing-imports==1.6.0]
        args: ['--select=E,F', '--exclude=src/filters, src/parser/evaql']

# -   repo: https://github.com/asottile/reorder_python_imports
#     rev: v2.3.0
#     hooks:
#     -   id: reorder-python-imports
#         args: [--py3-plus]
