name: eva_35
channels:
  - conda-forge
  - anaconda
  - defaults
  - pytorch
dependencies:
  - _tflow_1100_select=0.0.1=gpu
  - easydict=1.9=py_0
  - _tflow_select=2.1.0=gpu
  - absl-py=0.7.0=py36_0
  - astor=0.7.1=py36_0
  - blas=1.0=mkl
  - bzip2=1.0.6=h14c3975_5
  - c-ares=1.15.0=h7b6447c_1
  - ca-certificates=2019.1.23=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.3.9=py36_0
  - cffi=1.12.2=py36h2e261b9_1
  - contextlib2=0.5.5=py36_0
  - cudatoolkit=9.2=0
  - cudnn=7.3.1=cuda9.2_0
  - cupti=9.2.148=0
  - cycler=0.10.0=py36_0
  - cython=0.29.6=py36he6710b0_0
  - dbus=1.13.6=h746ee38_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - gast=0.2.2=py36_0
  - glib=2.56.2=hd408876_0
  - graphite2=1.3.13=h23475e2_0
  - grpcio=1.16.1=py36hf8bcb03_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - h5py=2.8.0=py36h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.1=144
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - keras=2.2.4=0
  - keras-applications=1.0.7=py_0
  - keras-base=2.2.4=py36_0
  - keras-preprocessing=1.0.9=py_0
  - kiwisolver=1.0.1=py36hf484d3e_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.36=hbc83047_0
  - libprotobuf=3.6.0=hdbcaa40_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - libxslt=1.1.33=h7d1a2b0_0
  - lxml=4.3.2=py36hefd8a0e_0
  - markdown=3.0.1=py36_0
  - matplotlib=3.0.3=py36h5429711_0
  - mkl=2019.1=144
  - mkl_fft=1.0.10=py36ha843d7b_0
  - mkl_random=1.0.2=py36hd81dba3_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.8.2=py36h6bb024c_1
  - numpy=1.16.2=py36h7e9f1db_0
  - numpy-base=1.16.2=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1b=h7b6447c_1
  - pandas=0.24.2=py36he6710b0_0
  - pcre=8.43=he6710b0_0
  - pillow=5.4.1=py36h34e0f95_0
  - pip=19.0.3=py36_0
  - pixman=0.38.0=h7b6447c_0
  - protobuf=3.6.0=py36hf484d3e_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pycparser=2.19=py36_0
  - pyparsing=2.3.1=py36_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.8=h0371630_0
  - python-dateutil=2.8.0=py36_0
  - pytorch=1.0.1=cuda92py36h65efead_0
  - pytorch-cpu
  - pytz=2018.9=py36_0
  - pyyaml=5.1=py36h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.20.3=py36hd81dba3_0
  - scipy=1.2.1=py36h7c811a0_0
  - setuptools=40.8.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sqlite=3.27.2=h7b6447c_0
  - tensorboard=1.12.2=py36he6710b0_0
  - tensorflow=1.12.0=gpu_py36he74679b_0
  - tensorflow-base=1.12.0=gpu_py36had579c0_0
  - tensorflow-gpu=1.12.0=h0d30ee6_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hbc83047_0
  - torchvision=0.2.1=py36_0
  - tornado=6.0.1=py36h7b6447c_0
  - werkzeug=0.14.1=py36_0
  - wheel=0.33.1=py36_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pycodestyle
  - pytest-cov
  - antlr4-python3-runtime=4.7=py36_0
  - pip:
      - torch==1.0.1
prefix: eva_35

