name: eva
channels:
  - conda-forge
  - anaconda
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pip
  - numpy
  - opencv
  - scikit-learn
  - pandas
  - coveralls
  - coverage
  - pytest-cov
  - autopep8
  - autoflake
  - torchvision=1.6.0
  - pytorch=0.7.0
  - tensorflow
  - tensorboard
  - pillow=6.1
  - sqlalchemy
  - pymysql
  - sqlalchemy-utils
  - mock
  - pytest-asyncio
  - flake8
  - sphinx 
  - sphinx_rtd_theme
  - pip:
    - antlr4-python3-runtime==4.8
    - petastorm
    - pre-commit
prefix: eva
