name: eva
channels:
  - conda-forge
  - anaconda
  - defaults
  - pytorch
dependencies:
  - python=3.7
  - pip
  - numpy
  - opencv
  - scikit-learn
  - pandas
  - coveralls
  - coverage
  - pytest-cov
  - pycodestyle
  - autopep8
  - autoflake
  - torchvision
  - pytorch
  - tensorflow
  - tensorboard
  - pillow=6.1
  - sqlalchemy
  - pymysql
  - sqlalchemy-utils
  - mock
  - pylint
  - pytest-asyncio
  - pip:
    - antlr4-python3-runtime==4.8
    - petastorm
    - pre-commit-hooks
prefix: eva
