name: eva
channels:
  - conda-forge
  - anaconda
  - defaults
  - pytorch
dependencies:
  - python=3.7.6
  - pip
  - numpy
  - opencv
  - scikit-learn
  - pandas
  - coveralls
  - coverage
  - pytest-cov
  - autopep8
  - autoflake
  - pytorch::torchvision
  - pytorch::pytorch
  - tensorflow
  - tensorboard
  - pillow=6.1
  - sqlalchemy
  - pymysql
  - sqlalchemy-utils
  - mock
  - pytest-asyncio
  - flake8
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - antlr4-python3-runtime==4.8
    - pyspark==3.0.2
    - petastorm
    - pre-commit
    - flake8
    - pytest
    - coveralls
prefix: eva
